apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
    - {name: clean-master01, address: *.*.*.70, internalAddress: *.*.*.70, user: account, password: ""}
    - {name: clean-node01, address: *.*.*.71, internalAddress: *.*.*.71, user: account, password: ""}
    - {name: clean-node02, address: *.*.*.72, internalAddress: *.*.*.72, user: account, password: ""}
    - {name: clean-node03, address: *.*.*.73, internalAddress: *.*.*.73, user: account, password: ""}
  roleGroups:
    etcd:
      - clean-master01
    control-plane:
      - clean-master01
    worker:
      - clean-node01
      - clean-node02
      - clean-node03
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.21.9
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: docker
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []